# Generated by Django 4.0.3 on 2022-06-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='category_date_created',
            new_name='brand_date_created',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='category_name',
            new_name='brand_name',
        ),
    ]
