# Generated by Django 4.0.3 on 2022-06-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_status',
            field=models.CharField(default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_status',
            field=models.CharField(default=0, max_length=5, null=True),
        ),
    ]
