# Generated by Django 4.0.3 on 2022-05-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
    ]
