# Generated by Django 4.0.3 on 2022-05-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_username_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code_payment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
