# Generated by Django 4.0.3 on 2022-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_voucher_status_voucher_voucher_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_quantity',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
