# Generated by Django 4.0.3 on 2022-05-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_voucher_voucher_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='username',
            new_name='user',
        ),
    ]
